# Generated by Django 4.1.1 on 2022-09-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=255)),
                ("Title", models.CharField(max_length=255)),
                ("Price", models.FloatField()),
                ("Img", models.CharField(max_length=255)),
            ],
        ),
    ]
